services:
  db:
    image: postgres
    container_name: some_postgres
    restart: always
    environment:
      POSTGRES_DB: gorm
      POSTGRES_USER: fazt
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  postgres_data: # Defines a named volume for data persistence
